### ISSUE TITLE
Set Export default frequency to Lowest Available

### ISSUE THREAD

**Issue by tkingimf** [tkingimf/Diver#11]

**Comment by chammontree** [comment]
Will the date range always be *,* for this?:
                    freq:?,
                    start_date:*,
                    end_date:*

**Comment by tkingimf** [comment]
I was thinking they could still choose a date range but I guess that wouldn't make sense unless it was just the highest level, years

**Comment by chammontree** [comment]
I set this to Common for default.  
For both '?' and '@' you will get the annual formatted start and end date.

**Comment by tkingimf** [comment]
Lowest Available and common sending annual, this is on PHP end
