### ISSUE TITLE
Export Options

### ISSUE THREAD

**Issue by chammontree** [tkingimf/Diver#138]
- Frequency (all, a, q, m, d)
- Dimensions
- Date Range
- Orientation
- Missing Values

**Comment by tkingimf** [comment]
$settings:{
 'missing_value': string (default = ""),
'table_format': string   (default = "Diver"),
'apply_scale': boolean  (default = false),
'orientation': string (default = "rows")  (defaults to rows unless value is exactly "columns"),
}

these will all work, though table_format doesn't change anything yet

more to come

**Comment by chammontree** [comment]
Can we make apply scale an integer that defaults to 0
and
Frequency an array ie ["annual","quarterly"] or ["monthly"]

**Comment by tkingimf** [comment]
updated: 


$settings:{
'missing_value': string (default = ""),
'table_format': string (default = "diver"),
'apply_scale': varchar (default = "default" ),
'orientation': string (default = "rows") (defaults to rows unless value is exactly "columns"),
'response_type': string(default="json"),
'start_date': varchar (default = null = "*"),
'end_date': varchar (default = null = "*")
},
$page_by:{
  'key1': array (default = [] = ["*"]),
  'keyn': array (default = [] = ["*"]),
}  assoc_array (default = array("frequency":["*"])
