### ISSUE TITLE
Parent and sibling for dimension

### ISSUE THREAD

**Issue by tkingimf** [tkingimf/Diver#27]
Doesn't seem to be working

**Comment by chammontree** [comment]
Done.  But can the api always pass parent and sibling as array

**Comment by tkingimf** [comment]
When do you want me to switch it? I assume it won't work if I change it to an array now.

**Comment by chammontree** [comment]
You can switch it whenever. Its a one line change on my end

**Comment by tkingimf** [comment]
I've changed it to an array now
