### ISSUE TITLE
Check csd database and remove all slicers from filter causes TypeError

### ISSUE THREAD

**Issue by chammontree** [tkingimf/Diver#294]
![divercsdslicererror](https://cloud.githubusercontent.com/assets/19555537/23731158/e7b506cc-0439-11e7-9f05-9391b2976e73.png)

**Comment by chammontree** [comment]
If nick showed you how to reproduce this can you show me?

**Comment by tkingimf** [comment]
I fixed all their headers, he's testing again next week so hopefully no issues. Can't reproduce
