### ISSUE TITLE
Memory Issues: PHP processes hanging in memory

### ISSUE THREAD

**Issue by chammontree** [tkingimf/Diver#323]
![image](https://cloud.githubusercontent.com/assets/19555537/25259680/833cf4ea-2615-11e7-80ce-44ba41f451a5.png)

Shouldn't be a problem on production but let be mindefule of it

**Comment by tkingimf** [comment]
We'll keep looking into ways to limit the SQL query memory, but closing for now after fixing what seem to be the major pressure points
