### ISSUE TITLE
Change Response in Logs

### ISSUE THREAD

**Issue by tkingimf** [tkingimf/Diver#56]

**Comment by tkingimf** [comment]
check on method and what to record for each method *ie put could be too large)

**Comment by tkingimf** [comment]
type = endpoint-log
@timestamp = entrytime in UTC milliseconds
request:{
user:{
name:string
id:number
dept:string
},
body: json_encode request,
endpoint: string,
headers: array of objects
},
host_name:server name,
version: apiversion,
stat: object  time,memory,file size etc,
execution_time:milliseconds,
response:{
\endpointname\:array
...
},
cache_resources:{
\endpointname\:count of ids from cache
},
error:{
code: code string,
severity: [0-3]
},
spawn_logs: array of reference to child logs

**Comment by tkingimf** [comment]
type = database-usage-log
@timestamp = entrytime in UTC milliseconds
request:{
user:{
name:string
id:number
dept:string
}
},
database:api_id string,
response:{
\endpointname:array
}

**Comment by chammontree** [comment]
"mappings": {
    "endpoint_transaction_log": {
      "_all":{
        "enabled":false
      },
      "properties": {
        "@timestamp": {
          "type": "date"
        },
        "host_name": {
          "type": "keyword"
        },
        "version":{
          "type": "keyword" 
        },
        "stats":{
          "type": "object",
          "enabled": false
        },
        "spawn_logs":{
          "type": "keyword"  
        },
        "execution_time":{
          "type": "integer"
        },
        "error":{
          "properties": {
            "code": {
              "type": "keyword"
            },
            "severity": {
              "type": "byte"
            }
          }
        },
        "request":{
          "properties": {
            "user":{
              "properties":{
                "id":{
                  "type": "keyword"
                },
                "name":{
                  "type": "keyword"
                },
                "dept":{
                  "type": "text",
                  "fields": {
                    "raw":{
                      "type": "keyword"
                    }
                  }
                }
              }
            },
            "endpoint":{
              "type": "keyword"
            },
            "body":{
              "type": "text",
              "index": false
            },
            "headers":{
              "properties":{
                "name":{
                  "type": "keyword"
                },
                "value":{
                  "type": "text",
                  "index_options": "docs"
                }
              }
            }
          }
        }
      }
    },
    "database_usage_log":{
      "_all": {
        "enabled":false
      },
      "properties":{
        "@timestamp": {
          "type": "date"
        },
        "request":{
          "properties": {
            "user":{
              "properties":{
                "id":{
                  "type": "keyword"
                },
                "name":{
                  "type": "keyword"
                },
                "dept":{
                  "type": "text",
                  "fields": {
                    "raw":{
                      "type": "keyword"
                    }
                  }
                }
              }
            }
          }
        },
        "database":{
          "type":"text",
          "index_options": "docs",
          "fields":{
            "raw":{
              "type": "keyword"
            }
          }
        }
      }
    }
  }

**Comment by chammontree** [comment]
If you change your types to use "_" I created the dev-logs index you can start using
