### ISSUE TITLE
Ability to Send Up Array of Log Tags in API

### ISSUE THREAD

**Issue by chammontree** [tkingimf/Diver#61]
It would be useful if we could pass up tags like ["load_blance_test", "bot1", "delete"] in the api so we could parse and clean the logs more easily:
{
  request:{},
  log_tags:[]
}
or
{
request:{}, 
  meta:{
    log_tags:[]
  }
}

**Comment by tkingimf** [comment]
I pretty much have that set up for when I did the bots, I'll add a more formal way to do it though

**Comment by tkingimf** [comment]
request:{}, 
meta:{
log_tags:[]
}

can be used now. right now it's found under request.log_tags. Can modify this as part of the change log issue

**Comment by tkingimf** [comment]
can send log_tags: [
environment:"" for example
]

I can set which custom log tags we can allow.
